### ISSUE TITLE
docs: incorrect quickstart commands for helm chart installation

### ISSUE THREAD

**Issue by wallhided** [kafbat/ui-docs#10]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/kafbat/kafka-ui/issues) and [here](https://github.com/kafbat/helm-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/kafbat/kafka-ui/blob/master/.github/SECURITY.md)

### Describe the bug (actual behavior)

[Quickstart quide](https://ui.docs.kafbat.io/configuration/helm-charts/quick-start) for helm chart has incorrect commands

```helm install kafbat-ui kafbat-ui/kafbat-ui``` is incorrect which lead to helm error.

```
d.miroshnik@MacBook-Pro-admin ~ % helm install kafbat-ui kafbat-ui/kafbat-ui
Error: INSTALLATION FAILED: chart "kafbat-ui" matching  not found in kafbat-ui index. (try 'helm repo update'): no chart name found
```

### Expected behavior

Chart name inside repo is **kafka-ui**. 
The command should be following:
```
helm install kafbat-ui kafbat-ui/kafka-ui
```

Proof:

```
d.miroshnik@MacBook-Pro-admin ~ % helm search repo kafbat-ui
NAME              	CHART VERSION	APP VERSION	DESCRIPTION
kafbat-ui/kafka-ui	1.4.0        	v1.0.0     	A Helm chart for kafka-UI
```

### Your installation details

1. latest
2. latest
3. -
4. -

### Steps to reproduce

Follow current quickstart guide for helm charts

**Comment by Haarolean** [comment]
Hi, feel free to submit a PR, thanks!

**Comment by Haarolean** [comment]
#11
