### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by mirabtellegen** [kafbat/ui-docs#20]
Hi, I am familiar with your project and I noticed that it does not have a license. I would like to suggest that you add a license to your project so it can be freely used, modified, repurposed, or shared by the open source community. It seems like you already intend for this to be Open Source, since the README identifies it as a community open source project. You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/).

**Comment by Haarolean** [comment]
Hi, we're distribute our docs under the same license as the project, so it's Apache 2.0. I've added a LICENSE file to this particular repo to address this issue, thanks.
