### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by likeMyCoffee** [kafbat/ui-docs#9]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Quick start says
helm install kafbat-ui kafbat-ui/kafbat-ui
should be
helm install kafbat-ui kafbat-ui/kafka-ui

### Expected behavior

Install the helm chart

### Your installation details

None yet

### Steps to reproduce

Read documentation
Execute: helm install kafbat-ui kafbat-ui/kafbat-ui
See it do INSTALLATION FAILED
Execute: helm install kafbat-ui kafbat-ui/kafka-ui
See it install the chart :-)

### Screenshots

N/A

### Logs

N/A

**Comment by Haarolean** [comment]
@likeMyCoffee would you be able to submit a PR for this please?

**Comment by likeMyCoffee** [comment]
Yeah why not ☺️

**Comment by Haarolean** [comment]
#11
